# Generated by Django 6.0.7 on 2026-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=13)),
                ('profile_pic', models.ImageField(default='', upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDetail',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=55, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(default='', upload_to='managerpic')),
            ],
        ),
        migrations.DeleteModel(
            name='Customerdetails',
        ),
    ]
