# Generated by Django 6.0.7 on 2026-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0002_customerdetail_managerdetail_delete_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=45)),
                ('meals_included', models.TextField()),
                ('duration', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
