# Generated by Django 6.0.7 on 2026-08-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0003_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_image',
            field=models.ImageField(default='meal_plan/default.jpg', upload_to='meal_plan/'),
            preserve_default=False,
        ),
    ]
