# Generated by Django 6.0.7 on 2026-08-10 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0005_alter_mealplan_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='plan_image',
            field=models.ImageField(default='', upload_to='meal_plan/'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_status', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.customerdetail')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.mealplan')),
            ],
        ),
    ]
