# Generated by Django 6.0.7 on 2026-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0006_alter_mealplan_plan_image_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upiid', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
