# Generated by Django 6.0.7 on 2026-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0007_upidetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_plan/'),
        ),
    ]
